import type { HeaderArt } from '@/components/PageHeader'
import credits from './art-credits.json'

/**
 * Decorative header art for the home page and the section indexes.
 *
 * These are official press screenshots used as page furniture and nothing
 * else. No source says which place, person or creature any of them shows, so
 * none of them is ever attached to a record: a picture above the words
 * "Laslea Glen" reads as a claim that it is Laslea Glen, and this site cannot
 * make a claim it cannot source. Index pages name a whole section rather than
 * one thing, which is why they can carry art and record pages cannot.
 *
 * The credit strings are generated by tools/make-art.mjs and include, where
 * the press original was stamped with one, the build-state disclaimer the crop
 * removed from the image itself.
 */
const BANDS: Record<string, { src: string; credit: string }> = credits.bands

export function sectionArt(name: string, tall = false): HeaderArt | undefined {
  const band = BANDS[name]
  if (!band) return undefined
  return { src: band.src, credit: band.credit, tall }
}
