import fs from 'fs'
import path from 'path'
import type { HeaderArt } from '@/components/PageHeader'
import credits from './art-credits.json'

/**
 * Decorative header art for the home page and the section indexes.
 *
 * These are official press screenshots used as page furniture and nothing
 * else. No source says which place, person or creature any of them shows, so
 * none of them is ever attached to a record: a picture above the words
 * "Laslea Glen" reads as a claim that it is Laslea Glen, and this site cannot
 * make a claim it cannot source. Index pages name a whole section rather than
 * one thing, which is why they can carry art and record pages cannot.
 *
 * The credit strings are generated by tools/make-art.mjs and include, where
 * the press original was stamped with one, the build-state disclaimer the crop
 * removed from the image itself.
 *
 * ## These belong to one game
 *
 * Every band here was cut from a Dawnwalker press screenshot. That was
 * implicit while there was one wiki and became a hazard with seven: rendering
 * this set on the Onimusha home would put Bandai Namco's art on a Capcom page,
 * which is not a decorative liberty but a misattribution — and one a reader
 * might reasonably mistake for a claim about the game they are reading about.
 *
 * `ART_GAME` names the owner so callers can check before using it. Every other
 * wiki takes its art from its own game record.
 */
export const ART_GAME = 'dawnwalker'
const BANDS: Record<string, { src: string; credit: string }> = credits.bands

export function sectionArt(name: string, tall = false): HeaderArt | undefined {
  const band = BANDS[name]
  if (!band) return undefined
  return { src: band.src, credit: band.credit, tall }
}

/**
 * A front-page tile's picture, cut from that wiki's own game.
 *
 * `sectionArt` above is Dawnwalker's band set and stays that way, so for every
 * other wiki the honest options were its own screenshots or nothing. It was
 * nothing for a while, and seven front pages were a grid of flat boxes with an
 * icon in the corner - correct about attribution and plain enough to read as
 * unfinished.
 *
 * `tools/make-tile-art.mjs` cuts these from `assets/_games/<slug>/`, so a
 * wiki only ever shows its own game. The existence check is a filesystem read
 * at build time rather than a fetch: these are static files under `public/`,
 * a missing one would render as a broken tile, and a tile with no picture is
 * a better failure than a tile with a broken one.
 */
const TILE_ROOT = path.resolve('public/wiki-assets')

export function tileArt(game: string, name: string): string | undefined {
  const file = path.join(TILE_ROOT, game, 'tiles', `${name}.jpg`)
  return fs.existsSync(file) ? `/wiki-assets/${game}/tiles/${name}.jpg` : undefined
}
