/**
 * The email adapter Payload actually sends through.
 *
 * `email.ts` decides *what* is configured, without touching the network, and
 * is unit-tested on its own. This is the half that opens sockets, so it is
 * deliberately thin: pick a provider, wrap it once, and make every failure say
 * something a person holding a `.env` file can act on.
 *
 * Two things here exist because the library defaults are the failure this
 * project keeps meeting — something that looks successful and does nothing:
 *
 *   1. `nodemailerAdapter()` called with no transport quietly invents an
 *      **ethereal.email** test account. Mail "sends", the API returns success,
 *      and every message lands in a throwaway inbox nobody opens. We build the
 *      transport ourselves so that path can never be reached.
 *   2. `nodemailerAdapter`'s own `verify` step catches its error and
 *      `console.error`s it. A relay that refuses the credentials therefore
 *      boots clean and fails on the first password reset instead. We verify
 *      ourselves and throw.
 */

import { nodemailerAdapter } from '@payloadcms/email-nodemailer'
import { resendAdapter } from '@payloadcms/email-resend'
import nodemailer from 'nodemailer'
import type { EmailAdapter, SendEmailOptions } from 'payload'

import {
  fromHeader,
  mailgunEndpoint,
  resolveEmailSettings,
  resolveSender,
  type EmailEnv,
  type EmailSender,
  type EmailSettings,
} from './email'

/** Every address in a nodemailer `to`/`cc`/`bcc`, flattened to strings. */
const addressList = (value: SendEmailOptions['to']): string[] => {
  if (!value) return []
  const one = (entry: unknown): string =>
    typeof entry === 'string' ? entry : ((entry as { address?: string })?.address ?? '')
  return (Array.isArray(value) ? value : [value]).map(one).filter(Boolean)
}

/** The bare address out of a `Name <address>` header, or of a plain one. */
const addressOf = (value: SendEmailOptions['from']): string => {
  if (!value) return ''
  if (typeof value !== 'string') return value.address ?? ''
  const angled = value.match(/<([^>]+)>/)
  return (angled ? angled[1] : value).trim()
}

/*
  Site settings, cached for a minute.

  The sender is an admin field (Site settings → Legal & contact), so it has to
  be read per message rather than at boot — otherwise changing it needs a
  redeploy, which is the thing docs/COPY.md exists to prevent. A minute is long
  enough that a burst of password resets is one query, and short enough that an
  editor who changes the address sees it take effect before they go looking for
  the bug.
*/
type StoredSender = { fromName?: string | null; fromAddress?: string | null; replyTo?: string | null }

/*
  Read structurally rather than through the generated `SiteSetting` type.

  `src/payload-types.ts` is regenerated by `pnpm generate:types`, and this file
  has to compile both before and after that runs — otherwise adding the three
  sender fields is a change that cannot be committed in one piece. Reading the
  three keys defensively costs nothing and removes the ordering problem.
*/

const CACHE_MS = 60_000
let cached: { at: number; value: StoredSender } | null = null

type MinimalPayload = {
  findGlobal: (args: { slug: 'site-settings'; depth?: number }) => Promise<Record<string, unknown>>
  logger: { info: (msg: unknown) => void; warn: (msg: unknown) => void }
}

const storedSender = async (payload: MinimalPayload): Promise<StoredSender> => {
  if (cached && Date.now() - cached.at < CACHE_MS) return cached.value
  try {
    const settings = await payload.findGlobal({ slug: 'site-settings', depth: 0 })
    const value: StoredSender = {
      fromName: (settings.emailFromName as string | null) ?? null,
      fromAddress: (settings.emailFromAddress as string | null) ?? null,
      replyTo: (settings.emailReplyTo as string | null) ?? null,
    }
    cached = { at: Date.now(), value }
    return value
  } catch (error) {
    /*
      A database that cannot be read must not stop a password reset going out.
      The environment already holds a complete, validated sender — that is why
      EMAIL_FROM_ADDRESS is required rather than optional — so falling back to
      it loses the editor's wording and nothing else. Warned rather than
      swallowed: a findGlobal that fails here is a real problem elsewhere.
    */
    payload.logger.warn(
      `Could not read the sender from Site settings; using EMAIL_FROM_ADDRESS. ${String(error)}`,
    )
    return {}
  }
}

/** Only for tests and `pnpm email:test`, which must not see a stale read. */
export const clearSenderCache = (): void => {
  cached = null
}

/**
 * Wrap a provider adapter so every message leaves with the resolved sender.
 *
 * Payload's auth operations build the `from` header themselves, out of the
 * adapter's `defaultFromName` and `defaultFromAddress`, before we ever see the
 * message — so an editor's change in the admin would otherwise never reach an
 * actual email. We replace that header, and only that header: a `from` the
 * caller set to something else is left alone, because one day a call site will
 * mean it.
 */
const withResolvedSender = (
  settings: EmailSettings,
  inner: EmailAdapter<unknown>,
): EmailAdapter<unknown> => {
  return ({ payload }) => {
    const adapter = inner({ payload })
    return {
      ...adapter,
      sendEmail: async (message: SendEmailOptions) => {
        const sender = resolveSender(
          settings.sender,
          await storedSender(payload as unknown as MinimalPayload),
        )
        const ours = !message.from || addressOf(message.from) === settings.sender.address

        return adapter.sendEmail({
          ...message,
          ...(ours ? { from: fromHeader(sender) } : {}),
          ...(message.replyTo || !sender.replyTo ? {} : { replyTo: sender.replyTo }),
          /*
            One inbox for every message, for a staging deployment pointed at a
            copy of the production database. Applied here rather than through
            each provider's own `overrideRecipientAddress` so that it covers
            all four of them identically — an override that works on three
            providers out of four is worse than none.
          */
          ...(settings.overrideRecipient ? { to: settings.overrideRecipient, cc: undefined, bcc: undefined } : {}),
        })
      },
    }
  }
}

/**
 * The default, and the behaviour of a fresh clone with no credentials at all.
 *
 * Payload's own console adapter prints the recipient and the subject. That is
 * not enough to work with locally: the only thing anybody wants out of a
 * password-reset email in development is the link, and hunting it out of a
 * database column is why nobody tests the flow. So this prints the links too,
 * and says in as many words that nothing was delivered.
 */
const consoleAdapter = (settings: EmailSettings): EmailAdapter<unknown> => {
  return ({ payload }) => ({
    name: 'console',
    defaultFromAddress: settings.sender.address,
    defaultFromName: settings.sender.name ?? '',
    sendEmail: async (message: SendEmailOptions) => {
      const body = `${message.html ?? ''}${message.text ?? ''}`
      const links = [...String(body).matchAll(/https?:\/\/[^\s"'<>]+/g)].map((match) => match[0])
      payload.logger.info(
        [
          'EMAIL NOT SENT — EMAIL_PROVIDER is "console", so this was printed and discarded.',
          `  from:    ${String(message.from ?? '')}`,
          `  to:      ${addressList(message.to).join(', ')}`,
          message.replyTo ? `  replyTo: ${String(message.replyTo)}` : null,
          `  subject: ${message.subject ?? ''}`,
          ...links.map((link) => `  link:    ${link}`),
        ]
          .filter(Boolean)
          .join('\n'),
      )
      return { delivered: false as const }
    },
  })
}

/**
 * Mailgun, over its HTTP API.
 *
 * Hand-rolled where Resend and SMTP are not, because Payload ships no Mailgun
 * adapter and the alternative — Mailgun's SMTP endpoint through nodemailer —
 * needs a *different credential*: the per-domain SMTP password, not the API
 * key the dashboard hands you. Sending people to the `smtp` provider with an
 * API key in `SMTP_PASSWORD` would be an authentication failure with no
 * explanation. (If SMTP credentials are what you have, `EMAIL_PROVIDER=smtp`
 * against `smtp.mailgun.org` works and is documented in docs/EMAIL.md.)
 *
 * The other reason is the region. It is one character of difference in the
 * hostname and a total delivery failure, so it is built here, from a value
 * validated at boot, rather than left to a default.
 */
const mailgunAdapter = (
  settings: Extract<EmailSettings, { provider: 'mailgun' }>,
): EmailAdapter<unknown> => {
  const endpoint = mailgunEndpoint(settings.region, settings.domain)
  const auth = `Basic ${Buffer.from(`api:${settings.apiKey}`).toString('base64')}`

  return () => ({
    name: 'mailgun-rest',
    defaultFromAddress: settings.sender.address,
    defaultFromName: settings.sender.name ?? '',
    sendEmail: async (message: SendEmailOptions) => {
      const form = new FormData()
      form.append('from', typeof message.from === 'string' ? message.from : fromHeader(settings.sender))
      for (const to of addressList(message.to)) form.append('to', to)
      for (const cc of addressList(message.cc)) form.append('cc', cc)
      for (const bcc of addressList(message.bcc)) form.append('bcc', bcc)
      form.append('subject', message.subject ?? '')
      if (message.html) form.append('html', String(message.html))
      if (message.text) form.append('text', String(message.text))
      for (const replyTo of addressList(message.replyTo as SendEmailOptions['to'])) {
        form.append('h:Reply-To', replyTo)
      }

      const response = await fetch(endpoint, { method: 'POST', headers: { Authorization: auth }, body: form })
      const raw = await response.text()

      if (!response.ok) {
        /*
          Mailgun's own words, verbatim, because paraphrasing them is how a
          404 "Domain not found" gets reported as "email failed". The region
          hint is appended on 401 specifically: an EU domain addressed at the
          US endpoint answers 401, which reads as a bad key and is debugged as
          one for an afternoon.
        */
        let detail = raw
        try {
          const parsed = JSON.parse(raw) as { message?: string }
          if (parsed.message) detail = parsed.message
        } catch {
          // Not JSON — an HTML error page or an empty body. Keep it as it came.
        }
        const hint =
          response.status === 401 || response.status === 404
            ? ` — check MAILGUN_REGION (currently "${settings.region}") and that MAILGUN_DOMAIN "${settings.domain}" exists in that region`
            : ''
        throw new Error(`Mailgun ${response.status}: ${detail || response.statusText}${hint}`)
      }

      try {
        return JSON.parse(raw) as unknown
      } catch {
        return { raw }
      }
    },
  })
}

const smtpAdapter = async (
  settings: Extract<EmailSettings, { provider: 'smtp' }>,
): Promise<EmailAdapter<unknown>> => {
  const transport = nodemailer.createTransport({
    host: settings.host,
    port: settings.port,
    secure: settings.secure,
    ...(settings.user && settings.password
      ? { auth: { user: settings.user, pass: settings.password } }
      : {}),
  })

  /*
    Dialled at boot, and a failure is fatal.

    `@payloadcms/email-nodemailer` does run `verify()`, but catches the error
    and logs it, so bad credentials produce a clean start and a password reset
    that goes nowhere a fortnight later. Refusing to start is louder and
    cheaper: the person who just pasted the credentials is still at the
    terminal. The cost is that an unreachable relay stops `pnpm build` — which
    is the correct time to find out, and is written down in docs/EMAIL.md.
  */
  try {
    await transport.verify()
  } catch (error) {
    throw new Error(
      `SMTP_HOST ${settings.host}:${settings.port} refused the connection or the credentials: ${
        error instanceof Error ? error.message : String(error)
      }`,
    )
  }

  return await nodemailerAdapter({
    transport,
    skipVerify: true, // Already done above, with the error kept.
    defaultFromAddress: settings.sender.address,
    defaultFromName: settings.sender.name ?? '',
  })
}

const providerAdapter = async (settings: EmailSettings): Promise<EmailAdapter<unknown>> => {
  switch (settings.provider) {
    case 'console':
      return consoleAdapter(settings)
    case 'mailgun':
      return mailgunAdapter(settings)
    case 'resend':
      return resendAdapter({
        apiKey: settings.apiKey,
        defaultFromAddress: settings.sender.address,
        defaultFromName: settings.sender.name ?? '',
      }) as EmailAdapter<unknown>
    case 'smtp':
      return await smtpAdapter(settings)
  }
}

/**
 * Build the adapter for `payload.config.ts`.
 *
 * Throws `EmailConfigError` — naming the variable — rather than starting with
 * mail that cannot work. That is the whole point: the app refusing to boot is
 * a message somebody reads, and an email that vanishes is not.
 */
export const buildEmailAdapter = async (
  env: EmailEnv = process.env as EmailEnv,
): Promise<EmailAdapter<unknown>> => {
  try {
    const settings = resolveEmailSettings(env)
    return withResolvedSender(settings, await providerAdapter(settings))
  } catch (error) {
    /*
      Printed before it is rethrown, because of where this lands.

      This runs at the top of `payload.config.ts`, so an unhandled throw here
      surfaces as a module-load stack trace with the real sentence four frames
      down — read by most people as "the config is broken" rather than as "you
      set one variable wrong". The stack still goes out; this just puts the
      answer above it.
    */
    // eslint-disable-next-line no-console
    console.error(
      [
        '',
        '  Email is not configured correctly, so the app will not start.',
        '',
        `  ${error instanceof Error ? error.message : String(error)}`,
        '',
        '  Set EMAIL_PROVIDER=console (or remove it) to run without email at all.',
        '  docs/EMAIL.md has the variables for each provider.',
        '',
      ].join('\n'),
    )
    throw error
  }
}

export type { EmailSender }
