import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { Shell } from '@/components/Shell'
import type { RailItem } from '@/components/SiteRail'
import type { FooterColumn } from '@/components/SiteFooter'
import { getGame, getPublishedGames, getSiteSettings, gameUrl } from '@/lib/payload'
import { sectionsFor, toolsFor } from '@/lib/sections'
import { fanProjectNote } from '@/lib/credit'
import { hub } from '@/lib/urls'
import { Analytics } from '@/components/Analytics'
import { resolveTags, verificationMetadata } from '@/lib/tags'

/**
 * One game's wiki.
 *
 * Readers never see this segment in a URL. `proxy.ts` maps
 * `dawnwalker.example.com/quests` onto `/dawnwalker/quests`, so the prefix is
 * internal routing and every link in the site stays root-relative — which is
 * why several hundred existing `<Link href="/quests/…">` did not have to
 * change when the site became a network.
 */

type Props = { params: Promise<{ game: string }> }

/**
 * Generated here rather than in each child page, so the thirteen index pages
 * and thirteen detail pages below do not each repeat the list of games. A
 * child's own `generateStaticParams` is then called once per game, with that
 * game in `params`.
 */
export async function generateStaticParams() {
  const games = await getPublishedGames()
  return games.map((game) => ({ game: game.slug }))
}

/**
 * A slug that is not a published game is a 404, not a fallback.
 *
 * Without this, an unknown slug would render at request time and the scoped
 * query would throw deep inside a page. Worse, it would let `/about` be
 * interpreted as a game if the static route above it ever moved.
 */
export const dynamicParams = false

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { game: slug } = await params
  const game = await getGame(slug)
  if (!game) return {}

  const base = await gameUrl(game)
  const name = game.shortTitle || game.title

  return {
    // Each wiki is its own site as far as search engines are concerned, so it
    // gets its own canonical origin, its own title template and its own feeds.
    metadataBase: new URL(base),
    title: {
      /*
        `absolute`, not `default`: a default is augmented by the closest
        parent's template, and this wiki's name is the whole title. `template`
        still applies to child pages, which is what gives every record page its
        "· Onimusha Wiki" suffix.
      */
      absolute: game.seo?.title || `${game.title} guide, wiki and database`,
      template: `%s · ${name} Wiki`,
    },
    description: game.seo?.description || game.summary || undefined,
    applicationName: `${name} Wiki`,
    // This wiki's own Search Console token, falling back to the network's.
    // Google will not accept the apex's token on a subdomain.
    verification: verificationMetadata(await resolveTags(slug)),
    /*
      This wiki's own icons and share card, generated by
      `tools/make-wiki-icons.mjs` from the publisher's capsule and hero art.

      Without these every host served the same favicon and the same og.png,
      both cut from Dawnwalker — so eight tabs looked identical and sharing an
      Onimusha page put another publisher's key art on the preview.
    */
    icons: {
      icon: [
        { url: `/wiki-assets/${slug}/icon-32.png`, type: 'image/png', sizes: '32x32' },
        { url: `/wiki-assets/${slug}/icon-512.png`, type: 'image/png', sizes: '512x512' },
      ],
      apple: `/wiki-assets/${slug}/apple-touch-icon.png`,
    },
    openGraph: {
      siteName: `${name} Wiki`,
      type: 'website',
      locale: 'en',
      images: [
        {
          url: `/wiki-assets/${slug}/og.jpg`,
          width: 1200,
          height: 630,
          alt: `${game.title}${game.publisher ? ` — ${game.publisher}` : ''}`,
        },
      ],
    },
    twitter: { card: 'summary_large_image', images: [`/wiki-assets/${slug}/og.jpg`] },
    alternates: {
      canonical: '/',
      types: {
        'application/rss+xml': [{ url: '/feed.xml', title: `${name} Wiki` }],
        'application/atom+xml': [{ url: '/atom.xml', title: `${name} Wiki` }],
      },
    },
  }
}

export default async function GameLayout({
  children,
  params,
}: Props & { children: React.ReactNode }) {
  const { game: slug } = await params
  const game = await getGame(slug)
  if (!game || game.status === 'planned') notFound()

  const settings = await getSiteSettings()
  const tags = await resolveTags(slug)
  const sections = await sectionsFor(slug)
  const tools = toolsFor(game)
  const name = game.shortTitle || game.title

  /*
    The way back to the network.

    Every wiki is its own host, so `/` on a wiki is that wiki's front page and
    there was no link anywhere in the chrome that reached the hub - a reader
    who arrived on a Gears page from a search had no way to discover the other
    seven except by editing the address bar. The footer carried "All wikis",
    which is the sitemap rather than the navigation, and nobody scrolls to a
    footer to go up a level.

    It sits last so it reads as leaving rather than as one more section of this
    wiki, and it is `external` because it points at a different host.
  */
  const rail: RailItem[] = [
    { label: 'Home', href: '/', icon: 'home' },
    ...tools,
    ...sections.map(({ label, href, icon }) => ({ label, href, icon })),
    {
      label: `All ${settings.siteName} wikis`,
      href: hub('/'),
      icon: 'external',
      external: true,
    },
  ]

  /*
    The footer is the site map, so it is built from the same derived section
    list the rail is — split into three columns by hand because "Plan a run"
    and "Database" are meaningfully different to a reader in a way that a
    mechanical split into equal thirds would not be.
  */
  const database = sections.filter((section) =>
    ['regions', 'characters', 'enemies', 'items', 'courts'].includes(section.collection),
  )
  const systems = sections.filter((section) =>
    ['endings', 'court-activities', 'perks', 'skill-trees', 'mechanics'].includes(section.collection),
  )
  const planning = sections.filter((section) =>
    ['quests', 'builds', 'guides'].includes(section.collection),
  )

  const columns: FooterColumn[] = [
    {
      heading: 'Plan a run',
      links: [...tools, ...planning].map(({ label, href }) => ({ label, href })),
    },
    { heading: 'Database', links: database.map(({ label, href }) => ({ label, href })) },
    { heading: 'Systems', links: systems.map(({ label, href }) => ({ label, href })) },
    {
      /*
        The first three are this wiki's own pages; the rest live once, on the
        hub, so they are absolute. A relative `/privacy` on a wiki host is a
        404 — the network's legal pages exist at the apex only, because seven
        copies of a privacy policy is seven pages competing for one search and
        six of them going stale.
      */
      heading: 'This site',
      links: [
        { label: 'About the data', href: '/about' },
        { label: 'Report an error', href: '/corrections' },
        { label: 'Request a feature', href: '/requests' },
        { label: 'All wikis', href: hub('/wikis') },
        { label: 'Contributors', href: hub('/authors') },
        { label: 'Contact', href: hub('/contact') },
        { label: 'Your account', href: hub('/account') },
        { label: 'Privacy', href: hub('/privacy') },
        { label: 'Terms', href: hub('/terms') },
      ],
    },
  ].filter((column) => column.links.length > 0)

  return (
    <Shell
      siteName={`${name} Wiki`}
      items={rail}
      footer={{
        blurb:
          game.summary ||
          `A guide and database for ${game.title}. Every figure carries a confidence rating, and where sources disagree we say so rather than picking one.`,
        columns,
        // This wiki's own disclaimer, not the network's. See `fanProjectNote`.
        note: fanProjectNote(game, settings.footerNote),
        maintainer: settings.maintainer,
        legalEntity: settings.legalEntity,
        postalAddress: settings.postalAddress,
        contactEmail: settings.contactEmail,
      }}
    >
      {children}
      <Analytics tags={tags} />
    </Shell>
  )
}
