import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { Shell } from '@/components/Shell'
import type { RailItem } from '@/components/SiteRail'
import type { FooterColumn } from '@/components/SiteFooter'
import { client, getGame, getPublishedGames, getSiteSettings, gameUrl } from '@/lib/payload'
import { slugify } from '@/fields/shared'
import { sectionsFor, toolsFor } from '@/lib/sections'
import { fanProjectNote } from '@/lib/credit'
import { JsonLd } from '@/components/JsonLd'
import { networkOrganization, videoGame, webSite } from '@/lib/schema'
import { clamp } from '@/lib/seo'
import { hub } from '@/lib/urls'
import { networkHome } from '@/lib/network-home'
import { Analytics } from '@/components/Analytics'
import { resolveTags, verificationMetadata } from '@/lib/tags'

/**
 * One game's wiki.
 *
 * Readers never see this segment in a URL. `proxy.ts` maps
 * `dawnwalker.example.com/quests` onto `/dawnwalker/quests`, so the prefix is
 * internal routing and every link in the site stays root-relative — which is
 * why several hundred existing `<Link href="/quests/…">` did not have to
 * change when the site became a network.
 */

type Props = { params: Promise<{ game: string }> }

/**
 * Generated here rather than in each child page, so the thirteen index pages
 * and thirteen detail pages below do not each repeat the list of games. A
 * child's own `generateStaticParams` is then called once per game, with that
 * game in `params`.
 */
export async function generateStaticParams() {
  const games = await getPublishedGames()
  return games.map((game) => ({ game: game.slug }))
}

/**
 * A wiki added after the build still works.
 *
 * This was `false`, so only the game slugs known at build time rendered and
 * anything else was a permanent 404. That quietly made a documented promise
 * untrue: `docs/NETWORK.md` says adding a wiki is "create a row in the admin,
 * write content. No deploy, no DNS change, no code" — and a ninth wiki created
 * in the admin on a live deployment answered 404 on every request until
 * somebody rebuilt. Records behaved correctly the whole time; only a *new
 * game* was blocked, which is the one case nobody tested because it is the
 * rarest.
 *
 * Turning it on is safe because the guard it was standing in for is real and
 * lives below: the layout calls `notFound()` for a slug that is not a
 * published game, so an unknown one is still a 404 — it is just decided by
 * the database rather than by a list frozen at build time. `/about` and its
 * siblings cannot be captured either: a static segment wins over a dynamic
 * one in Next's routing, and `APEX_ONLY` in `proxy.ts` reserves those names
 * against a game ever claiming them.
 */
export const dynamicParams = true

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { game: slug } = await params
  const game = await getGame(slug)
  if (!game) return {}

  const base = await gameUrl(game)
  const name = game.shortTitle || game.title

  return {
    // Each wiki is its own site as far as search engines are concerned, so it
    // gets its own canonical origin, its own title template and its own feeds.
    metadataBase: new URL(base),
    title: {
      /*
        `absolute`, not `default`: a default is augmented by the closest
        parent's template, and this wiki's name is the whole title. `template`
        still applies to child pages, which is what gives every record page its
        "· Onimusha Wiki" suffix.
      */
      absolute: game.seo?.title || `${game.title} guide, wiki and database`,
      template: `%s · ${name} Wiki`,
    },
    /*
      Clamped. A game summary is written for the page, where length is fine;
      a description over about 165 characters is cut mid-sentence in a result,
      and the wiki home was the longest on the network at 196.
    */
    description: clamp(game.seo?.description || game.summary || '') || undefined,
    applicationName: `${name} Wiki`,
    // This wiki's own Search Console token, falling back to the network's.
    // Google will not accept the apex's token on a subdomain.
    verification: verificationMetadata(await resolveTags(slug)),
    /*
      This wiki's own icons and share card, generated by
      `tools/make-wiki-icons.mjs` from the publisher's capsule and hero art.

      Without these every host served the same favicon and the same og.png,
      both cut from Dawnwalker — so eight tabs looked identical and sharing an
      Onimusha page put another publisher's key art on the preview.
    */
    icons: {
      icon: [
        { url: `/wiki-assets/${slug}/icon-32.png`, type: 'image/png', sizes: '32x32' },
        { url: `/wiki-assets/${slug}/icon-512.png`, type: 'image/png', sizes: '512x512' },
      ],
      apple: `/wiki-assets/${slug}/apple-touch-icon.png`,
    },
    openGraph: {
      siteName: `${name} Wiki`,
      type: 'website',
      locale: 'en',
      images: [
        {
          url: `/wiki-assets/${slug}/og.jpg`,
          width: 1200,
          height: 630,
          alt: `${game.title}${game.publisher ? ` — ${game.publisher}` : ''}`,
        },
      ],
    },
    twitter: { card: 'summary_large_image', images: [`/wiki-assets/${slug}/og.jpg`] },
    alternates: {
      canonical: '/',
      types: {
        'application/rss+xml': [{ url: '/feed.xml', title: `${name} Wiki` }],
        'application/atom+xml': [{ url: '/atom.xml', title: `${name} Wiki` }],
      },
    },
  }
}

export default async function GameLayout({
  children,
  params,
}: Props & { children: React.ReactNode }) {
  const { game: slug } = await params
  const game = await getGame(slug)
  if (!game || game.status === 'planned') notFound()

  const settings = await getSiteSettings()
  const tags = await resolveTags(slug)
  const sections = await sectionsFor(slug)
  // The wiki's own origin, for the structured data below.
  const canonical = await gameUrl(game)
  const tools = toolsFor(game)
  const name = game.shortTitle || game.title

  /*
    The picture and the company profiles the structured data points at.

    `knownCompanies` is the set of slugs the companies host actually has a page
    for, so a developer named on the record resolves to that page's `@id` and
    the graph joins across hosts. A name with no profile degrades to a plain
    Organization rather than to an `@id` that 404s — a dangling reference is
    worse than an unlinked one, because a consumer will follow it.
  */
  const poster =
    game.profile?.poster && typeof game.profile.poster === 'object'
      ? (game.profile.poster as { url?: string | null })
      : null
  const hero =
    game.theme?.hero && typeof game.theme.hero === 'object'
      ? (game.theme.hero as { url?: string | null })
      : null
  const rawImage = poster?.url ?? hero?.url ?? null
  const schemaImage = rawImage
    ? rawImage.startsWith('http')
      ? rawImage
      : `${canonical}${rawImage}`
    : null

  const payload = await client()
  const companyRows = await payload.find({
    collection: 'companies',
    where: {
      or: [game.developer, game.publisher]
        .flatMap((value) => (value ?? '').split(','))
        .map((value) => value.trim())
        .filter(Boolean)
        .map((value) => ({ slug: { equals: slugify(value) } })),
    },
    limit: 20,
    depth: 0,
  })
  const knownCompanies = new Set<string>(companyRows.docs.map((row) => String(row.slug)))


  const rail: RailItem[] = [
    { label: 'Home', href: '/', icon: 'home' },
    ...tools,
    ...sections.map(({ label, href, icon }) => ({ label, href, icon })),
    /*
      Extra links an editor added, under the derived sections and above the way
      out. Deliberately additive: the sections above come from `sectionsFor`,
      which returns only indexes with records in them, and nothing typed here
      can add one — a rail entry pointing at an empty index reads as a broken
      site, which is why that list is derived and stays derived.
    */
    ...(settings.railItems ?? []).map((item) => ({
      label: item.label,
      href: item.href,
      icon: item.icon ?? 'book',
      external: /^https?:\/\//i.test(item.href),
    })),
  ]

  /*
    The footer is the site map, so it is built from the same derived section
    list the rail is — split into three columns by hand because "Plan a run"
    and "Database" are meaningfully different to a reader in a way that a
    mechanical split into equal thirds would not be.
  */
  const database = sections.filter((section) =>
    ['regions', 'characters', 'enemies', 'items', 'courts'].includes(section.collection),
  )
  const systems = sections.filter((section) =>
    ['endings', 'court-activities', 'perks', 'skill-trees', 'mechanics'].includes(section.collection),
  )
  const planning = sections.filter((section) =>
    ['quests', 'builds', 'guides'].includes(section.collection),
  )

  const builtInColumns: FooterColumn[] = [
    {
      heading: 'Plan a run',
      links: [...tools, ...planning].map(({ label, href }) => ({ label, href })),
    },
    { heading: 'Database', links: database.map(({ label, href }) => ({ label, href })) },
    { heading: 'Systems', links: systems.map(({ label, href }) => ({ label, href })) },
    {
      /*
        The first three are this wiki's own pages; the rest live once, on the
        hub, so they are absolute. A relative `/privacy` on a wiki host is a
        404 — the network's legal pages exist at the apex only, because seven
        copies of a privacy policy is seven pages competing for one search and
        six of them going stale.
      */
      heading: 'This site',
      links: [
        { label: 'About the data', href: '/about' },
        { label: 'Report an error', href: '/corrections' },
        { label: 'Request a feature', href: '/requests' },
        { label: 'All wikis', href: hub('/wikis') },
        { label: 'Contributors', href: hub('/authors') },
        { label: 'Contact', href: hub('/contact') },
        { label: 'Your account', href: hub('/account') },
        { label: 'Privacy', href: hub('/privacy') },
        { label: 'Terms', href: hub('/terms') },
      ],
    },
  ]

  /*
    An editor's own columns replace the derived ones outright rather than
    merging with them. Merging would be the friendlier default and the wrong
    one: the built-in columns are this wiki's section list, so a merge means
    every column an editor writes is followed by links they cannot remove, and
    the way to drop one becomes "edit the code". All or nothing is a rule
    somebody can hold in their head; blank keeps what shipped.

    Empty columns are dropped either way — a heading with nothing under it is
    what a wiki with no tools would otherwise print.
  */
  const columns: FooterColumn[] = (
    settings.footerColumns && settings.footerColumns.length > 0
      ? settings.footerColumns.map((column) => ({
          heading: column.heading,
          links: (column.links ?? []).map(({ label, href }) => ({ label, href })),
        }))
      : builtInColumns
  ).filter((column) => column.links.length > 0)

  return (
    <Shell
      siteName={`${name} Wiki`}
      items={rail}
      networkHome={await networkHome()}
      footer={{
        blurb:
          game.summary ||
          `A guide and database for ${game.title}. Every figure carries a confidence rating, and where sources disagree we say so rather than picking one.`,
        columns,
        // This wiki's own disclaimer, not the network's. See `fanProjectNote`.
        note: fanProjectNote(game, settings.footerNote),
        maintainer: settings.maintainer,
        legalEntity: settings.legalEntity,
        postalAddress: settings.postalAddress,
        contactEmail: settings.contactEmail,
      }}
    >
      {children}
      {/*
        The wiki's own identity, once, on every page of it.

        `videoGame` and `breadcrumbs` have existed in `components/JsonLd.tsx`
        since early on and neither had a single caller: 140 of 152 sampled
        pages carried no structured data at all, and the only ones that did
        were guides. A site that argues it is the accurate, sourced one and
        then tells search engines nothing about what it is describing is
        leaving the argument unmade in the one place it is read by machine.

        It goes in the layout rather than on each page because the layout is
        where the canonical origin is already computed, and because what it
        says - which game this site is about, and who made it - is true of
        every page under it.
      */}
      <JsonLd
        data={videoGame(canonical, game, {
          image: schemaImage,
          description: game.summary,
          knownCompanies: knownCompanies,
        })}
      />
      {/*
        The site and its publisher, which is what the game entity hangs off.

        Without a `WebSite` there is no root to the graph: a `VideoGame` on its
        own says what this page is about and nothing about what this site is,
        so a consumer has no way to tell eight wikis apart from eight pages.
      */}
      <JsonLd
        data={webSite(canonical, {
          name: `${game.shortTitle || game.title} Wiki`,
          description: game.summary,
          searchPath: '/search',
        })}
      />
      <JsonLd
        data={networkOrganization({
          name: settings.siteName,
          legalEntity: settings.legalEntity,
          email: settings.contactEmail,
        })}
      />
      <Analytics tags={tags} />
    </Shell>
  )
}
