import 'dotenv/config'
import fs from 'fs'
import path from 'path'
import { createHash } from 'crypto'
import { fileURLToPath } from 'url'
import { getPayload } from 'payload'
import type { CollectionSlug, Payload } from 'payload'

import config from '../payload.config'
import { PRIMARY_GAME } from './games'

/**
 * Attaches the generated emblems to perks, endings, builds, courts, court
 * activities and skill trees.
 *
 *   pnpm make:emblems && pnpm seed:emblems
 *
 * ## What is being attached, and why it is allowed here
 *
 * These six collections are the ones docs/ASSETS.md leaves with nothing: no
 * press material identifies a perk or an ending, `assets/` has no folder for
 * any of them, and every record falls back to the shared icon set.
 *
 * The rule that keeps a screenshot off a record page is about claims, not
 * licences — a photograph above "Walking Fortress" reads as a picture *of*
 * Walking Fortress whatever the alt text says, and nothing published names its
 * own subjects. `tools/make-emblems.mjs` draws flat geometry from the record's
 * slug instead. There is nothing depicted in it, so there is no claim in it,
 * and the credit below says so in as many words rather than leaving a reader
 * to work it out.
 *
 * That is also why `mediaCredit()` is not used here. It attributes art to the
 * publisher who owns it, which would be false twice over: the publisher did
 * not make these and does not own them.
 *
 * Idempotent. A record that already has an image is left alone; `--force`
 * replaces an emblem with a freshly generated one, and deliberately will not
 * replace anything else — see below.
 */

const dirname = path.dirname(fileURLToPath(import.meta.url))
const ASSET_DIR = path.resolve(dirname, '..', '..', 'assets')
const FORCE = process.argv.includes('--force')

/**
 * Collection -> the folder its emblems were written to, and the field that
 * holds the image.
 *
 * All six call it `image` today, which is exactly why it is written out per
 * collection rather than assumed: `characters` calls the same thing `portrait`
 * and a seventh collection added here would silently write a field that does
 * not exist.
 *
 * `skill-trees` reads from `skills` because that is the folder name
 * `src/seed/assets.ts` already maps onto the collection, and two spellings for
 * one collection is how a folder ends up skipped with a warning nobody reads.
 */
const TARGETS: { collection: CollectionSlug; folder: string; field: string }[] = [
  { collection: 'perks', folder: 'perks', field: 'image' },
  { collection: 'endings', folder: 'endings', field: 'image' },
  { collection: 'builds', folder: 'builds', field: 'image' },
  { collection: 'courts', folder: 'courts', field: 'image' },
  { collection: 'court-activities', folder: 'court-activities', field: 'image' },
  { collection: 'skill-trees', folder: 'skills', field: 'image' },
]

/** Every emblem's filename starts with this, which is what makes an emblem
 *  recognisable later — see the `--force` guard. */
const PREFIX = `${PRIMARY_GAME}-emblem-`

/**
 * The one sentence a reader gets if they ask where the picture came from.
 *
 * Says it is ours, says it is generated, and says it shows nothing — because a
 * credit that only said "generated" would still leave the picture looking like
 * a claim about the record, which is the whole thing this is designed around.
 */
const CREDIT =
  'Emblem generated by this site from the record name. Abstract geometry: it is not game art and does not depict anything in the game.'

/**
 * The name an emblem's media row gets: the record it belongs to, plus eight
 * characters of the picture's own content.
 *
 * The content half is the load-bearing part. Keying on the record name alone
 * makes any change to `tools/make-emblems.mjs` invisible — the tool redraws
 * all 103 files, `uploadOnce` finds every name already taken, reuses the old
 * rows, and the run reports success while the site serves the previous
 * pictures. Replacing the bytes in place does not fix it either: Payload
 * writes the replacement as `<name>-1.png` and renames the row to match, so
 * the next run misses the key entirely and starts a second copy.
 *
 * Content-addressed, both of those go away. Identical art resolves to the
 * identical row, so re-running attaches nothing new; changed art is a new name
 * and a clean upload, and `sweep()` takes the superseded row away afterwards.
 */
const filenameFor = (collection: string, slug: string, file: string): string => {
  const digest = createHash('sha1').update(fs.readFileSync(file)).digest('hex').slice(0, 8)
  return `${PREFIX}${collection}-${slug}-${digest}.png`
}

/**
 * Upload a file once and reuse it.
 *
 * Re-running must not fill the media library with copies of the same emblem —
 * which is what happened the first time an image pipeline was written for this
 * project. `src/seed/game-art.ts` carries the same guard for the same reason.
 */
async function uploadOnce(
  payload: Payload,
  file: string,
  filename: string,
  alt: string,
): Promise<number | string | null> {
  const existing = await payload.find({
    collection: 'media',
    where: { filename: { equals: filename } },
    limit: 1,
    depth: 0,
  })
  if (existing.docs.length > 0) return existing.docs[0].id

  try {
    const created = await payload.create({
      collection: 'media',
      data: { alt, credit: CREDIT } as never,
      file: {
        data: fs.readFileSync(file),
        mimetype: 'image/png',
        name: filename,
        size: fs.statSync(file).size,
      },
    })
    return created.id
  } catch (error) {
    console.error(`    upload failed for ${filename}: ${(error as Error).message}`)
    return null
  }
}

/**
 * Delete emblem media that no current emblem file corresponds to.
 *
 * Every regeneration of the artwork strands a whole generation of rows —
 * a hundred and three of them — and nothing else in the project would ever
 * look at them again. This is the relationship `seed:prune` has with the guide
 * generators: the pass that writes is also the pass that clears up after the
 * version of itself that came before.
 *
 * Scoped to the emblem prefix, so it can only ever reach rows this file wrote.
 */
async function sweep(payload: Payload, keep: Set<string>): Promise<number> {
  const rows = await payload.find({
    collection: 'media',
    where: { filename: { like: PREFIX } },
    limit: 2000,
    depth: 0,
  })

  let removed = 0
  for (const row of rows.docs as { id: string | number; filename?: string | null }[]) {
    if (!row.filename || keep.has(row.filename)) continue
    try {
      await payload.delete({ collection: 'media', id: row.id })
      removed += 1
    } catch (error) {
      console.error(`    could not remove ${row.filename}: ${(error as Error).message}`)
    }
  }
  return removed
}

/** The filename behind whatever is currently in the field, or undefined. */
async function currentFilename(
  payload: Payload,
  image: unknown,
): Promise<string | undefined> {
  if (image === null || image === undefined) return undefined
  if (typeof image === 'object' && 'filename' in (image as Record<string, unknown>)) {
    return (image as { filename?: string }).filename
  }
  try {
    const media = await payload.findByID({
      collection: 'media',
      id: image as string | number,
      depth: 0,
    })
    return (media as { filename?: string }).filename ?? undefined
  } catch {
    return undefined
  }
}

async function run(): Promise<void> {
  if (!fs.existsSync(ASSET_DIR)) {
    console.log('No assets/ directory. Run `node tools/make-emblems.mjs` first.')
    process.exit(0)
  }

  const payload = await getPayload({ config })

  /*
    Pinned to one game, the way `pnpm assets` is, and for the same reason:
    `assets/<folder>/<slug>.png` records no game, so matching a slug across the
    network would file Dawnwalker's emblem against whichever wiki happened to
    have a record with the same slug. All six collections are game-scoped and
    every record in them is Dawnwalker's today. A second wiki's emblems want a
    game level in the path first.
  */
  const game = await payload.find({
    collection: 'games',
    where: { slug: { equals: PRIMARY_GAME } },
    limit: 1,
    depth: 0,
  })
  if (game.docs.length === 0) {
    console.error(`No game "${PRIMARY_GAME}" in the database. Run \`pnpm seed\` first.`)
    process.exit(1)
  }
  const gameId = game.docs[0].id

  let attached = 0
  let skipped = 0
  let missing = 0
  const protectedRecords: string[] = []
  /** Every emblem filename this run stands behind, swept against at the end. */
  const current = new Set<string>()

  /*
    The sweep deletes emblem media that nothing in `current` vouches for, so it
    is only safe once every folder has been read. A missing assets/ folder
    would otherwise make the run delete that collection's emblems and blank the
    field on every record in it — the damage being done by the half of the job
    that did not happen.
  */
  let everyFolderRead = true

  for (const target of TARGETS) {
    const dir = path.join(ASSET_DIR, target.folder)
    if (!fs.existsSync(dir)) {
      console.log(`  ${target.collection.padEnd(17)} no assets/${target.folder}/ — run \`pnpm make:emblems\``)
      everyFolderRead = false
      continue
    }

    const records = await payload.find({
      collection: target.collection,
      where: { game: { equals: gameId } },
      limit: 500,
      depth: 0,
    })

    let done = 0
    for (const record of records.docs as unknown as (Record<string, unknown> & {
      id: string | number
      slug: string
      title?: string
    })[]) {
      const file = path.join(dir, `${record.slug}.png`)
      if (!fs.existsSync(file)) {
        missing += 1
        // Same reasoning as the folder guard: this record's emblem, if it has
        // one, was not vouched for by a file, so the sweep must not reach it.
        everyFolderRead = false
        continue
      }

      const filename = filenameFor(target.collection, record.slug, file)

      const existing = record[target.field]
      if (existing) {
        /*
          `--force` regenerates emblems; it does not overwrite pictures. If a
          record has since been given a real, sourced, identified image, an
          emblem is a downgrade — and a silent one, because both fields look
          identical from here. So the filename decides: ours starts with the
          prefix, anything else is somebody's editorial decision and is
          reported rather than replaced.
        */
        const held = await currentFilename(payload, existing)
        const isEmblem = held?.startsWith(PREFIX) ?? false

        if (isEmblem && held === filename) {
          // Already carrying exactly this picture. Nothing to do, --force or not.
          current.add(filename)
          skipped += 1
          continue
        }

        if (!FORCE || !isEmblem) {
          if (FORCE && !isEmblem) protectedRecords.push(`${target.collection}/${record.slug} (${held ?? 'unknown file'})`)
          /*
            Whatever the record still points at has to survive the sweep, even
            though this run would have drawn something else. Sweeping on the
            filenames this run *generated* rather than the ones records
            actually hold would delete the media under every record it just
            declined to touch, and leave a field pointing at nothing.
          */
          if (isEmblem && held) current.add(held)
          skipped += 1
          continue
        }
      }

      const mediaId = await uploadOnce(
        payload,
        file,
        filename,
        // Names the record and says what the picture is, so a screen reader
        // is not told there is a picture of something there isn't.
        `Generated emblem for ${record.title ?? record.slug} — abstract, not game art`,
      )
      if (!mediaId) continue
      current.add(filename)

      await payload.update({
        collection: target.collection,
        id: record.id,
        data: { [target.field]: mediaId } as never,
        depth: 0,
      })
      attached += 1
      done += 1
    }

    console.log(`  ${target.collection.padEnd(17)} ${String(done).padStart(3)} of ${records.docs.length}`)
  }

  const swept = everyFolderRead ? await sweep(payload, current) : 0

  console.log(
    `\n${attached} emblems attached, ${skipped} left alone${FORCE ? '' : ' (use --force to regenerate)'}.`,
  )
  if (swept > 0) console.log(`${swept} superseded emblem(s) removed from the media library.`)
  if (missing > 0) {
    console.log(
      `${missing} record(s) had no emblem file — re-run \`pnpm make:emblems\` after adding records.`,
    )
  }
  if (!everyFolderRead) {
    console.log('Superseded emblems were left in place: this run did not see the whole set.')
  }
  if (protectedRecords.length > 0) {
    console.log(`\n--force did not touch ${protectedRecords.length} record(s) holding a non-emblem image:`)
    for (const line of protectedRecords) console.log(`  - ${line}`)
    console.log('Clear the field in the admin if an emblem really is wanted there.')
  }
  process.exit(0)
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
