/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    players: PlayerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    quests: Quest;
    'court-activities': CourtActivity;
    endings: Ending;
    regions: Region;
    courts: Court;
    characters: Character;
    enemies: Enemy;
    'skill-trees': SkillTree;
    perks: Perk;
    items: Item;
    builds: Build;
    mechanics: Mechanic;
    guides: Guide;
    corrections: Correction;
    media: Media;
    players: Player;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    quests: QuestsSelect<false> | QuestsSelect<true>;
    'court-activities': CourtActivitiesSelect<false> | CourtActivitiesSelect<true>;
    endings: EndingsSelect<false> | EndingsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    courts: CourtsSelect<false> | CourtsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    enemies: EnemiesSelect<false> | EnemiesSelect<true>;
    'skill-trees': SkillTreesSelect<false> | SkillTreesSelect<true>;
    perks: PerksSelect<false> | PerksSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    builds: BuildsSelect<false> | BuildsSelect<true>;
    mechanics: MechanicsSelect<false> | MechanicsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    corrections: CorrectionsSelect<false> | CorrectionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Player | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PlayerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Quests and their time costs. Prereqs and exclusions here drive the run checker — keep them accurate.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests".
 */
export interface Quest {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  kind: 'main' | 'ally' | 'court' | 'side' | 'contract' | 'prologue';
  region?: (number | null) | Region;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  /**
   * Set when this quest angers a specific vassal.
   */
  court?: (number | null) | Court;
  /**
   * In segments. A full run is 480 (30 days × 16). Leave min/max equal when the cost is fixed.
   */
  time?: {
    min?: number | null;
    max?: number | null;
    confidence?: ('high' | 'medium' | 'low') | null;
    /**
     * Tick only when a source actually publishes this cost. Unticked means unknown — which is different from free, and the run checker reports it as a floor.
     */
    known?: boolean | null;
    /**
     * e.g. "Costs 2 extra segments if you take the shrine option."
     */
    note?: string | null;
  };
  /**
   * Some steps can only be taken as a human, others only as a vampire.
   */
  phase: 'day' | 'night' | 'either';
  /**
   * Must be finished before this one opens. The checker walks these transitively.
   */
  prereqs?: (number | Quest)[] | null;
  /**
   * Opens up once this is done. Used for internal linking.
   */
  unlocks?: (number | Quest)[] | null;
  /**
   * Permanently locked out by doing this one. The checker treats these as hard failures.
   */
  excludes?: (number | Quest)[] | null;
  affectsEndings?: (number | Ending)[] | null;
  rewards?:
    | {
        kind: 'item' | 'perk' | 'skillPoint' | 'currency' | 'story';
        label: string;
        item?: (number | null) | Item;
        id?: string | null;
      }[]
    | null;
  /**
   * Corruption gained or lost. Negative values reduce it.
   */
  corruption?: number | null;
  /**
   * Infamy gained. Drives Brencis’s Edicts.
   */
  infamy?: number | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The ten regions of Vale Sangora.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  /**
   * Which vassal holds this region, if any.
   */
  court?: (number | null) | Court;
  dangerRating?: ('starting' | 'moderate' | 'dangerous' | 'late') | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  caption?: string | null;
  /**
   * Attribution. Game screenshots and art belong to Bandai Namco / Rebel Wolves — credit them.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The three vassal courts. Court Activities hang off these.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts".
 */
export interface Court {
  id: number;
  /**
   * e.g. "Ambrus"
   */
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  /**
   * Total Court Activities in this court.
   */
  activityCount?: number | null;
  /**
   * Roughly what share of this court's activities must be completed before the duel unlocks. Reported as ~75%, unconfirmed.
   */
  angerThresholdPct?: number | null;
  /**
   * The duel at the end of this court.
   */
  bossEnemy?: (number | null) | Enemy;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enemies".
 */
export interface Enemy {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  isBoss?: boolean | null;
  region?: (number | null) | Region;
  weaknesses?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  phase?: ('day' | 'night' | 'either') | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Seven endings, gated three ways: by an ally, by a choice, or by the clock.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endings".
 */
export interface Ending {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  gate: 'ally' | 'choice' | 'clock';
  /**
   * The ally whose questline gates this ending.
   */
  ally?: (number | null) | Character;
  /**
   * Everything that must be completed to reach this ending. The checker walks prereqs from here, so listing only the questline itself is enough.
   */
  requiredQuests?: (number | Quest)[] | null;
  /**
   * True for "Time Runs Out" — reached by missing the deadline, not by choosing.
   */
  isFailure?: boolean | null;
  /**
   * True for endings that close the run early, before the Brencis confrontation.
   */
  isEarlyExit?: boolean | null;
  /**
   * What the player must DO. Not a spoiler — shown openly, because this is what someone mid-run came for.
   */
  howToGet?: string | null;
  /**
   * What actually HAPPENS in this ending. This is the spoiler, and it stays covered until the reader clicks to reveal it. Keep the two separate — it is the distinction every other site fails to make.
   */
  outcome?: string | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  role?: ('protagonist' | 'ally' | 'vassal' | 'antagonist' | 'merchant' | 'minor') | null;
  romanceable?: boolean | null;
  /**
   * Where they are usually found.
   */
  region?: (number | null) | Region;
  /**
   * Their questline, in order. Drives ally-gated endings.
   */
  questline?: (number | Quest)[] | null;
  portrait?: (number | null) | Media;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Legendaries, manuals, recipes and key items — not every one of the 1,700+ pickups.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  category: 'weapon' | 'armour' | 'ring' | 'manual' | 'recipe' | 'consumable' | 'ingredient' | 'quest';
  rarity?: ('legendary' | 'rare' | 'common') | null;
  region?: (number | null) | Region;
  /**
   * Where it is and what it takes to reach it.
   */
  howToGet?: string | null;
  /**
   * Named stat lines, e.g. "Attack stamina cost −12%".
   */
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "court-activities".
 */
export interface CourtActivity {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  court: number | Court;
  region?: (number | null) | Region;
  time?: {
    min?: number | null;
    max?: number | null;
  };
  phase?: ('day' | 'night' | 'either') | null;
  /**
   * How much this pushes the vassal toward the duel, where known.
   */
  angerValue?: number | null;
  howToStart?: string | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-trees".
 */
export interface SkillTree {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  /**
   * Witchcraft is a day tree, Vampirism a night tree, Swordmastery sits in the middle.
   */
  phase: 'day' | 'night' | 'either';
  /**
   * Vampirism unlocks as Corruption rises.
   */
  gatedByCorruption?: boolean | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Perks and skills. Each tree has three ultimates, of which only one can be taken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perks".
 */
export interface Perk {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  tree: number | SkillTree;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  /**
   * One ultimate per tree, nine in the game.
   */
  isUltimate?: boolean | null;
  /**
   * Segments spent learning this specific perk. LEAVE BLANK unless a source states it — blank renders as "not confirmed". Reporting says most skills cost about 1, but that general claim is not evidence for any individual perk.
   */
  timeCostSegments?: number | null;
  /**
   * Some perks must be unlocked out in the world rather than bought.
   */
  foundInWorld?: boolean | null;
  /**
   * What it actually does, in one line.
   */
  effect?: string | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Recommended builds. These seed the build planner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds".
 */
export interface Build {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Optional. A screenshot or piece of art for this record. Until one is set, the site falls back to its own icon, so a missing image never leaves a hole.
   */
  image?: (number | null) | Media;
  playstyle: 'day' | 'night' | 'hybrid';
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  primaryTree?: (number | null) | SkillTree;
  perks?: (number | Perk)[] | null;
  items?: (number | Item)[] | null;
  /**
   * Segments needed to learn the whole build, where known. Leave blank rather than estimate.
   */
  segmentCost?: number | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mechanics".
 */
export interface Mechanic {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Lower sorts first in the mechanics index.
   */
  order?: number | null;
  /**
   * The numbers a reader came for. Rendered as a table at the top of the page.
   */
  keyFacts?:
    | {
        label: string;
        value: string;
        confidence?: ('high' | 'medium' | 'low') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * URL segment. Auto-filled from the title. Changing it breaks existing links.
   */
  slug: string;
  /**
   * The search this page is written to answer. One page, one query.
   */
  targetQuery?: string | null;
  relatedQuests?: (number | Quest)[] | null;
  relatedEndings?: (number | Ending)[] | null;
  /**
   * Shown to readers as a badge. Be honest — it is the whole point of this site.
   */
  confidence: 'high' | 'medium' | 'low';
  /**
   * One or two sentences. Used on cards, in search results and as the page lede.
   */
  summary: string;
  /**
   * The main article. Original prose only — never paste from another site.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cite every figure. Two independent sources before marking confidence high.
   */
  sources?:
    | {
        title: string;
        url: string;
        retrieved?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to derive from the title and summary.
   */
  seo?: {
    /**
     * Under ~60 characters. Overrides the <title> tag.
     */
    title?: string | null;
    /**
     * Under ~155 characters. Overrides the meta description.
     */
    description?: string | null;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reader reports. Triage these — they are the accuracy loop.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections".
 */
export interface Correction {
  id: number;
  /**
   * What the reader says is wrong.
   */
  summary: string;
  detail?: string | null;
  /**
   * Page the report came from.
   */
  pageUrl?: string | null;
  /**
   * Evidence the reader offered, if any.
   */
  sourceUrl?: string | null;
  status?: ('new' | 'fixed' | 'rejected' | 'blocked') | null;
  /**
   * Internal. Never shown publicly.
   */
  editorNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reader accounts. These are site visitors, not editors — they have no admin access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  /**
   * Optional. Shown only to the player themselves.
   */
  displayName?: string | null;
  /**
   * The saved run: day, phase, and which quests are ticked. Written by the site, not by hand.
   */
  run?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Used to decide whether the browser or the server has the newer run.
   */
  runUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'players';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'quests';
        value: number | Quest;
      } | null)
    | ({
        relationTo: 'court-activities';
        value: number | CourtActivity;
      } | null)
    | ({
        relationTo: 'endings';
        value: number | Ending;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'courts';
        value: number | Court;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'enemies';
        value: number | Enemy;
      } | null)
    | ({
        relationTo: 'skill-trees';
        value: number | SkillTree;
      } | null)
    | ({
        relationTo: 'perks';
        value: number | Perk;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'builds';
        value: number | Build;
      } | null)
    | ({
        relationTo: 'mechanics';
        value: number | Mechanic;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'corrections';
        value: number | Correction;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'players';
        value: number | Player;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'players';
        value: number | Player;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests_select".
 */
export interface QuestsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  region?: T;
  image?: T;
  court?: T;
  time?:
    | T
    | {
        min?: T;
        max?: T;
        confidence?: T;
        known?: T;
        note?: T;
      };
  phase?: T;
  prereqs?: T;
  unlocks?: T;
  excludes?: T;
  affectsEndings?: T;
  rewards?:
    | T
    | {
        kind?: T;
        label?: T;
        item?: T;
        id?: T;
      };
  corruption?: T;
  infamy?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "court-activities_select".
 */
export interface CourtActivitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  court?: T;
  region?: T;
  time?:
    | T
    | {
        min?: T;
        max?: T;
      };
  phase?: T;
  angerValue?: T;
  howToStart?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endings_select".
 */
export interface EndingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  gate?: T;
  ally?: T;
  requiredQuests?: T;
  isFailure?: T;
  isEarlyExit?: T;
  howToGet?: T;
  outcome?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  court?: T;
  dangerRating?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts_select".
 */
export interface CourtsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  activityCount?: T;
  angerThresholdPct?: T;
  bossEnemy?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  role?: T;
  romanceable?: T;
  region?: T;
  questline?: T;
  portrait?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enemies_select".
 */
export interface EnemiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  isBoss?: T;
  region?: T;
  weaknesses?:
    | T
    | {
        value?: T;
        id?: T;
      };
  phase?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-trees_select".
 */
export interface SkillTreesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  phase?: T;
  gatedByCorruption?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perks_select".
 */
export interface PerksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tree?: T;
  image?: T;
  isUltimate?: T;
  timeCostSegments?: T;
  foundInWorld?: T;
  effect?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  rarity?: T;
  region?: T;
  howToGet?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  image?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds_select".
 */
export interface BuildsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  playstyle?: T;
  difficulty?: T;
  primaryTree?: T;
  perks?: T;
  items?: T;
  segmentCost?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mechanics_select".
 */
export interface MechanicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  keyFacts?:
    | T
    | {
        label?: T;
        value?: T;
        confidence?: T;
        id?: T;
      };
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  targetQuery?: T;
  relatedQuests?: T;
  relatedEndings?: T;
  confidence?: T;
  summary?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        retrieved?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections_select".
 */
export interface CorrectionsSelect<T extends boolean = true> {
  summary?: T;
  detail?: T;
  pageUrl?: T;
  sourceUrl?: T;
  status?: T;
  editorNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  displayName?: T;
  run?: T;
  runUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  /**
   * Default meta description for pages that do not set their own.
   */
  description?: string | null;
  /**
   * Your name or handle. Shown in the footer and on the about page. Readers and search engines both treat an anonymous guide site as lower quality — put a real name here. Left blank, nothing is shown.
   */
  maintainer?: string | null;
  /**
   * When the data was last checked over. Shown on the home page.
   */
  lastVerified?: string | null;
  /**
   * Canonical origin, e.g. https://example.com. Used for sitemap and canonical URLs. Overridden by NEXT_PUBLIC_SITE_URL when set.
   */
  domain?: string | null;
  /**
   * The person or company responsible for this site. Your real name or registered company name.
   */
  legalEntity?: string | null;
  /**
   * A working address people can actually reach you on.
   */
  contactEmail?: string | null;
  /**
   * Required by GDPR/UK GDPR if you have readers in the EU or UK. A registered office or service address is fine; do not publish a home address you do not want public.
   */
  postalAddress?: string | null;
  /**
   * Country whose law governs the terms, e.g. "England and Wales".
   */
  jurisdiction?: string | null;
  /**
   * Top navigation, in order.
   */
  primaryNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Disclaimer line in the footer.
   */
  footerNote?: string | null;
  heroHeading?: string | null;
  heroSubheading?: string | null;
  /**
   * Leave off until there is traffic and an approved ad account.
   */
  adsEnabled?: boolean | null;
  /**
   * e.g. AdSense ca-pub-XXXXXXXX.
   */
  adClientId?: string | null;
  /**
   * Plausible domain or GA4 measurement ID. Left blank, no analytics load.
   */
  analyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  maintainer?: T;
  lastVerified?: T;
  domain?: T;
  legalEntity?: T;
  contactEmail?: T;
  postalAddress?: T;
  jurisdiction?: T;
  primaryNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerNote?: T;
  heroHeading?: T;
  heroSubheading?: T;
  adsEnabled?: T;
  adClientId?: T;
  analyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}